# mkdir ~/lib/include/marble
cp *.h ~/lib/include/marble
cp blendings/*.h ~/lib/include/marble
cp geodata/*.h ~/lib/include/marble
cp geodata/data/*.h ~/lib/include/marble
cp geodata/graphicsitem/*.h ~/lib/include/marble
cp geodata/handlers/dgml/*.h ~/lib/include/marble
cp geodata/handlers/gpx/*.h ~/lib/include/marble
cp geodata/handlers/kml/*.h ~/lib/include/marble
cp geodata/handlers/osm-namefinder/*.h ~/lib/include/marble
cp geodata/parser/*.h ~/lib/include/marble
cp geodata/scene/*.h ~/lib/include/marble
cp geodata/writer/*.h ~/lib/include/marble
cp geodata/writers/kml/*.h ~/lib/include/marble
cp graphicsview/*.h ~/lib/include/marble
cp graphicsview/screengraphicsitem/*.h ~/lib/include/marble
cp Projections/*.h ~/lib/include/marble
cp routing/*.h ~/lib/include/marble
cp routing/instructions/*.h ~/lib/include/marble
